### ISSUE TITLE
Background color for Sub Item in Menu doesn't inherit from primary menu

### ISSUE THREAD

**Issue by yellatchris** [godaddy-wordpress/primer-child-escapade#64]
I have noticed on version 1.1.0 that when I add a sub menu item it reverts to black as the background color and doesn't inherit the color of the primary menu. The text color does come over to the sub item as expected.

**Comment by EvanHerman** [comment]
Hi @yellatchris 

Can you update to 1.1.2 and see if you are still encountering the same issue? If so I can do some testing and investigate.

Evan

**Comment by yellatchris** [comment]
Evan,

My dashboard is not giving me an option to update.  Is there a direct link
to a download that I can use to update the Theme?

Chris

**Comment by EvanHerman** [comment]
Hi @yellatchris 

You're not getting an update notification because this theme is not yet hosted on WordPress.org. You'll need to download the latest release from here on Github, and then manually upload your files via FTP, or uninstall and then re-install the theme from on the dashboard.

You can download releases from the releases section here: https://github.com/godaddy/wp-escapade-theme/releases

More specifically, the 1.1.2 release can be found here:
https://github.com/godaddy/wp-escapade-theme/releases/tag/v1.1.2

And a direct link to the Escapade v1.1.2 .zip:
https://github.com/godaddy/wp-escapade-theme/releases/download/v1.1.2/escapade.zip

Evan

**Comment by leavreality** [comment]
Yes I having the same truble, even edit the .sub-menu to make backgroud color white and it does seem to expect any custom css coding to it.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
